@baseUrl = http://localhost:3000/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDdkODk2MGNhMGExNTc5MDMzYWEwZmIiLCJpYXQiOjE2ODYwNDY1NzgsImV4cCI6MTY4NjA4OTc3OH0.xJGsaPBsmqsDZVWjCFLY2GeNeZSumzJ4Q7mOGe1iCjI
@address = delhi


###
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
    "name":"Test",
    "email":"test@gmail.com",
    "password":"Password@123",
    "mobile": "9876543210",
    "role":"Admin"
}

### Mobile Verification
POST {{baseUrl}}/auth/mobile-otp-verification
Content-Type: application/json

{
    "mobile": "9876543210",
    "otp" : "132621"
}

### E-mail Verification
POST {{baseUrl}}/auth/email-otp-verification
Content-Type: application/json

{
    "email":"test@gmail.com",
    "otp" : "132621"
}

### Login 
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email":"vinay12siwach@gmail.com",
    "password":"Password@123"
}

### LogOut
POST {{baseUrl}}/auth/logout
Content-Type: application/json
Authorization: bearer {{token}}

{}


### Get all user
GET {{baseUrl}}/user
Content-Type: application/json
Authorization: bearer {{token}}

### Adding Hotel

POST {{baseUrl}}/hotel
Content-Type: application/json
Authorization: bearer {{token}}

{
    "name":"Hotel 3",
    "contact":"9876543214",
    "price":"2099",
    "description":"Description 3",
    "address":"delhi",
    "image":"Image 3",
    "amenities":"Amenities 1",
    "totalRooms":25
}

### Get all hotels per page 
GET {{baseUrl}}/hotel
Content-Type: application/json

### Get a particular hotel by Id
GET {{baseUrl}}/hotel/647f05e52f6e60bf6e55fafe
Content-Type: application/json

### Create a Review on a particular hotel by it's Id
POST {{baseUrl}}/hotel/647dca85c0f25dc88acfe2b8/review
content-type: application/json
Authorization: Bearer {{token}}

{
    "comment": "First Review on Hotel 3"
}

### Delete a particular Hotel by Id
DELETE {{baseUrl}}/hotel/647f05e52f6e60bf6e55fafe
Content-Type: application/json
Authorization: Bearer {{token}}


### Booking
GET {{baseUrl}}/booking
content-type: application/json
Authorization: Bearer {{token}}

### Adding Hotel in Booking
POST {{baseUrl}}/booking
content-type: application/json
Authorization: Bearer {{token}}

{
    "hotelId":"647dcbf9923d6e3cd36f15af",
    "rooms":2
}

### Removing Hotel in Booking
DELETE  {{baseUrl}}/booking/647dcbf9923d6e3cd36f15af
content-type: application/json
Authorization: Bearer {{token}}

### Search by Location
GET {{baseUrl}}/hotel/search/address/{{address}}
content-type: application/json
Authorization: Bearer {{token}}