@baseUrl = http://localhost:3000/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDdlZmYyNTg3MzY1OTAwNWY4MzJiNjMiLCJpYXQiOjE2ODYxMzA2NTgsImV4cCI6MTY4NjE3Mzg1OH0.7SsFLf5TTJGdZUldMfjMDy_5pMGqpb2ZJ-IwFoE9fWo
@address = delhi
@minPrice = 5000
@maxPrice = 10000

@userId = 647d8960ca0a1579033aa0fb

@hotelId =64803ef03bd31bdffa7d0def

@bookingId =648030b64fa1417b4c89e52f


###
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
    "name":"Test2",
    "email":"test2@gmail.com",
    "password":"Password@123",
    "mobile": "98765243210"
}

### Mobile Verification
POST {{baseUrl}}/auth/mobile-otp-verification
Content-Type: application/json

{
    "mobile": "9876543210",
    "otp" : "132621"
}

### E-mail Verification
POST {{baseUrl}}/auth/email-otp-verification
Content-Type: application/json

{
    "email":"test@gmail.com",
    "otp" : "132621"
}

### Login 
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email":"test@gmail.com",
    "password":"Password@123"
}

### LogOut
POST {{baseUrl}}/auth/logout
Content-Type: application/json
Authorization: bearer {{token}}

{}


### Get all user
GET {{baseUrl}}/user
Content-Type: application/json
Authorization: bearer {{token}}


### Adding Hotel
POST {{baseUrl}}/hotel
Content-Type: application/json
Authorization: bearer {{token}}

{
    "name":"Hotel 4",
    "contact":"9876543214",
    "price":"2099",
    "description":"Description 3",
    "address":"delhi",
    "image":"Image 3",
    "amenities":"Amenities 1",
    "rooms":25
}

### Get all hotels per page 
GET {{baseUrl}}/hotel
Content-Type: application/json

### Get a particular hotel by Id
GET {{baseUrl}}/hotel/{{hotelId}}
Content-Type: application/json

### Create a Review on a particular hotel by it's Id
POST {{baseUrl}}/hotel/{{hotelId}}/review
content-type: application/json
Authorization: Bearer {{token}}

{
    "comment": "Third Review on Hotel 3",
    "rating": 5
}

### Delete a particular Hotel by Id
DELETE {{baseUrl}}/hotel/{{hotelId}}
Content-Type: application/json
Authorization: Bearer {{token}}


### Search by Location
GET {{baseUrl}}/hotel/search/address/{{address}}
content-type: application/json
Authorization: Bearer {{token}}


### Search by Price
GET {{baseUrl}}/hotel/search/price/{{minPrice}}/{{maxPrice}}
content-type: application/json
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/hotel/booking
Content-Type: application/json
Authorization: bearer {{token}}

{

    "hotelId":"{{hotelId}}",
    "userId":"{{userId}}",
    "checkInDate": "2023-06-22",
    "checkOutDate": "2023-06-21",
    "rooms": 25
}

###
DELETE {{baseUrl}}/hotel/booking/{{bookingId}}
Content-Type: application/json
Authorization: bearer {{token}}